trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ArtifactoryToolsInstaller@1
  inputs:
    artifactoryService: 'ecosys'
    cliInstallationRepo: 'jfrog-cli-remote'
    installExtractors: true
    extractorsInstallationRepo: 'extractors'
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'ecosys'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'