trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ArtifactoryGenericDownload@2
  inputs:
    connection: 'ecosys'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "generic-local/rabbit",
            "target": "./"
          }
        ]
      }
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    failNoOp: true
- task: ArtifactoryGenericUpload@1
  inputs:
    artifactoryService: 'ecosys'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "rabbit",
            "target": "generic-local/rabbit2"
          }
        ]
      }
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
    failNoOp: true
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'ecosys'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'