trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JFrogGradle@1
  inputs:
    gradleBuildFile: 'build.gradle'
    workDir: 'gradle-examples/gradle-example-ci-server'
    tasks: 'artifactoryPublish'
    artifactoryResolverService: 'ecosys-artifactory'
    sourceRepo: 'libs-release'
    artifactoryDeployerService: 'ecosys-artifactory'
    targetRepo: 'libs-release'
    useWrapper: true
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    javaHomeOption: 'JDKVersion'

- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'ecosys-artifactory'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'