trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ArtifactoryToolsInstaller@1
  inputs:
    artifactoryService: 'ecosys'
    cliInstallationRepo: 'jfrog-cli'
- task: ArtifactoryMaven@1
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    artifactoryResolverService: 'ecosys'
    targetResolveReleaseRepo: 'libs-release'
    targetResolveSnapshotRepo: 'libs-snapshot'
    artifactoryDeployService: 'ecosys'
    targetDeployReleaseRepo: 'libs-release-local'
    targetDeploySnapshotRepo: 'libs-snapshot-local'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true