trigger: none

pool:
  vmImage: 'windows-latest'

steps:
  - task: ArtifactoryNpm@2
    inputs:
      command: 'install'
      artifactoryService: 'ecosys'
      sourceRepo: 'npm'
      workingFolder: 'npm-example'
      arguments: '--verbose'
      collectBuildInfo: true
      threads: '1'
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
      includeEnvVars: true

  - task: ArtifactoryPublishBuildInfo@1
    inputs:
      artifactoryService: 'ecosys'
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
    
  - task: ArtifactoryXrayScan@1
    inputs:
      artifactoryService: 'ecosys'
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
      allowFailBuild: true