pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: ArtifactoryGradle@1
  inputs:
    buildFile: 'gradle-examples/gradle-example-ci-server/build.gradle'
    tasks: 'artifactoryPublish'
    artifactoryResolverService: 'ecosys'
    sourceRepo: 'libs-release'
    artifactoryDeployService: 'ecosys'
    targetRepo: 'libs-release-local'
    useWrapper: true
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true